services:

  api:

    restart: unless-stopped

    build: .

    container_name: flask_api

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -fsS http://localhost:5000/health || exit 1"
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    ports:
      - "5000:5000"

    env_file:
      - .env

    depends_on:
      db:
        condition:
          service_healthy

  db:
    image: mysql:8.4.6

    restart: unless-stopped

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${DB_PASSWORD}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

    container_name: mysql_db

    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: task_management

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
