services:

  api:
    build: .

    container_name: flask_api

    ports:
      - "5000:5000"

    env_file:
      - .env

    depends_on:
      db:
        condition:
          service_healthy

  db:
    image: mysql:8.4

    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

    container_name: mysql_db

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: Root123
      MYSQL_DATABASE: task_management

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
